import { NextRequest, NextResponse } from "next/server";
import { createSupabaseServer, createSupabaseAdmin } from "@/lib/supabase/server";
import { uploadToR2 } from "@/lib/r2";
import JSZip from "jszip";
import sharp from "sharp";

interface RouteContext {
  params: Promise<{ id: string }>;
}

export const maxDuration = 60;

export async function POST(_request: NextRequest, { params }: RouteContext) {
  const { id } = await params;

  const supabase = await createSupabaseServer();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const admin = createSupabaseAdmin();

  const { data: pack } = await admin
    .from("packs")
    .select(`
      *,
      categories!category_id(slug, name),
      pack_items(
        id, generation_id, is_exclusive, sort_order,
        generations(id, title, slug, prompt, image_url, style, content_type, category)
      )
    `)
    .eq("id", id)
    .single();

  if (!pack) {
    return NextResponse.json({ error: "Not found" }, { status: 404 });
  }

  if (pack.user_id !== user.id) {
    const { data: profile } = await admin
      .from("profiles")
      .select("is_admin")
      .eq("id", user.id)
      .single();
    if (!profile?.is_admin) {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }
  }

  const items = (pack.pack_items || []).sort(
    (a: { sort_order: number }, b: { sort_order: number }) => a.sort_order - b.sort_order,
  );

  if (items.length === 0) {
    return NextResponse.json({ error: "Pack must have at least one item" }, { status: 400 });
  }

  await admin
    .from("packs")
    .update({ zip_status: "building", is_published: true, visibility: pack.visibility || "public" })
    .eq("id", id);

  try {
    const zip = new JSZip();
    const contentTypesSet = new Set<string>();
    const formatsSet = new Set<string>();

    for (const item of items) {
      const gen = item.generations;
      if (!gen?.image_url) continue;

      const name = gen.slug || gen.title?.toLowerCase().replace(/[^a-z0-9]+/g, "-") || gen.id;

      try {
        const res = await fetch(gen.image_url);
        if (!res.ok) continue;
        const buffer = Buffer.from(await res.arrayBuffer());

        zip.file(`${name}.webp`, buffer);
        formatsSet.add("webp");

        try {
          const pngBuffer = await sharp(buffer).png().toBuffer();
          zip.file(`${name}.png`, pngBuffer);
          formatsSet.add("png");
        } catch {
          // skip PNG conversion if it fails
        }
      } catch {
        continue;
      }

      if (gen.content_type) contentTypesSet.add(gen.content_type);
    }

    const licenseText = `LICENSE — ${pack.title}
Generated by clip.art (https://clip.art)

These images are free for personal and commercial use.
No attribution required.

For questions, visit https://clip.art
`;

    const readmeText = `${pack.title}
${"=".repeat(pack.title.length)}

${pack.description || ""}

Items: ${items.length}
Formats: ${Array.from(formatsSet).join(", ").toUpperCase()}
Content Types: ${Array.from(contentTypesSet).join(", ")}

Downloaded from https://clip.art/design-bundles/${pack.categories?.slug || "all"}/${pack.slug}
`;

    zip.file("LICENSE.txt", licenseText);
    zip.file("README.txt", readmeText);

    const zipBuffer = await zip.generateAsync({ type: "nodebuffer", compression: "DEFLATE" });

    const categorySlug = pack.categories?.slug || "uncategorized";
    const key = `packs/${categorySlug}/${pack.slug}.zip`;
    const zipUrl = await uploadToR2(Buffer.from(zipBuffer), key, {
      contentType: "application/zip",
      cacheControl: "public, max-age=3600",
    });

    const coverUrl = pack.cover_image_url || items[0]?.generations?.image_url || null;

    await admin
      .from("packs")
      .update({
        zip_url: zipUrl,
        zip_status: "ready",
        item_count: items.length,
        content_types: Array.from(contentTypesSet),
        formats: Array.from(formatsSet),
        cover_image_url: coverUrl,
      })
      .eq("id", id);

    return NextResponse.json({
      success: true,
      zip_url: zipUrl,
      zip_status: "ready",
      item_count: items.length,
    });
  } catch (err) {
    console.error("ZIP build failed:", err);
    await admin
      .from("packs")
      .update({ zip_status: "failed" })
      .eq("id", id);

    return NextResponse.json({ error: "ZIP build failed" }, { status: 500 });
  }
}
