-- Migration: Import 29 existing images into Supabase
-- Run this in: Supabase Dashboard → SQL Editor

-- Food Images (6)
INSERT INTO images (title, slug, seo_slug, category, image_url, cloudinary_public_id, cloudinary_url, cloudinary_secure_url, published, published_at, file_format, tags)
VALUES 
  ('Pecan Pie Illustration', 'pecan-pie-illustration', 'pecan-pie-illustration', 'food', 'https://assets.codepen.io/9394943/pecan-pie-illustration.png', 'pecan-pie-illustration', 'https://assets.codepen.io/9394943/pecan-pie-illustration.png', 'https://assets.codepen.io/9394943/pecan-pie-illustration.png', true, CURRENT_TIMESTAMP, 'png', ARRAY['food']),
  ('Mexican Food Illustration', 'mexican-food-illustration', 'mexican-food-illustration', 'food', 'https://assets.codepen.io/9394943/mexican-food-illustration-whitebg-2.png', 'mexican-food-illustration', 'https://assets.codepen.io/9394943/mexican-food-illustration-whitebg-2.png', 'https://assets.codepen.io/9394943/mexican-food-illustration-whitebg-2.png', true, CURRENT_TIMESTAMP, 'png', ARRAY['food']),
  ('Mexican Food Tacos Illustration', 'mexican-food-tacos-illustration', 'mexican-food-tacos-illustration', 'food', 'https://assets.codepen.io/9394943/mexican-food-illustration-whitebg.png', 'mexican-food-tacos-illustration', 'https://assets.codepen.io/9394943/mexican-food-illustration-whitebg.png', 'https://assets.codepen.io/9394943/mexican-food-illustration-whitebg.png', true, CURRENT_TIMESTAMP, 'png', ARRAY['food']),
  ('Produce Basket Illustration', 'produce-basket-illustration', 'produce-basket-illustration', 'food', 'https://assets.codepen.io/9394943/produce-basket-illustration-white-bg.png', 'produce-basket-illustration', 'https://assets.codepen.io/9394943/produce-basket-illustration-white-bg.png', 'https://assets.codepen.io/9394943/produce-basket-illustration-white-bg.png', true, CURRENT_TIMESTAMP, 'png', ARRAY['food']),
  ('Thanksgiving Dinner Illustration', 'thanksgiving-dinner-illustration', 'thanksgiving-dinner-illustration', 'food', 'https://assets.codepen.io/9394943/thanksgiving-illustration-1-white-bg.png', 'thanksgiving-dinner-illustration', 'https://assets.codepen.io/9394943/thanksgiving-illustration-1-white-bg.png', 'https://assets.codepen.io/9394943/thanksgiving-illustration-1-white-bg.png', true, CURRENT_TIMESTAMP, 'png', ARRAY['food']),
  ('Pancake Breakfast Illustration', 'pancake-breakfast-illustration', 'pancake-breakfast-illustration', 'food', 'https://assets.codepen.io/9394943/pancake-illustration-1-white-bg.png', 'pancake-breakfast-illustration', 'https://assets.codepen.io/9394943/pancake-illustration-1-white-bg.png', 'https://assets.codepen.io/9394943/pancake-illustration-1-white-bg.png', true, CURRENT_TIMESTAMP, 'png', ARRAY['food']);

-- Christmas Images (6)
INSERT INTO images (title, slug, seo_slug, category, image_url, cloudinary_public_id, cloudinary_url, cloudinary_secure_url, published, published_at, file_format, tags)
VALUES 
  ('Sitting Santa Claus Illustration', 'sitting-santa-claus-illustration', 'sitting-santa-claus-illustration', 'christmas', 'https://assets.codepen.io/9394943/sitting-santa-illustration.png', 'sitting-santa-claus-illustration', 'https://assets.codepen.io/9394943/sitting-santa-illustration.png', 'https://assets.codepen.io/9394943/sitting-santa-illustration.png', true, CURRENT_TIMESTAMP, 'png', ARRAY['christmas']),
  ('Reindeer Christmas Clipart', 'reindeer-christmas-clipart', 'reindeer-christmas-clipart', 'christmas', 'https://assets.codepen.io/9394943/reindeer-clipart-white-bg.png', 'reindeer-christmas-clipart', 'https://assets.codepen.io/9394943/reindeer-clipart-white-bg.png', 'https://assets.codepen.io/9394943/reindeer-clipart-white-bg.png', true, CURRENT_TIMESTAMP, 'png', ARRAY['christmas']),
  ('Realistic Santa Claus Illustration', 'realistic-santa-claus-illustration', 'realistic-santa-claus-illustration', 'christmas', 'https://assets.codepen.io/9394943/life-like-santa-illustration-1-wbg.png', 'realistic-santa-claus-illustration', 'https://assets.codepen.io/9394943/life-like-santa-illustration-1-wbg.png', 'https://assets.codepen.io/9394943/life-like-santa-illustration-1-wbg.png', true, CURRENT_TIMESTAMP, 'png', ARRAY['christmas']),
  ('Smiling Christmas Elves Clipart', 'smiling-christmas-elves-clipart', 'smiling-christmas-elves-clipart', 'christmas', 'https://assets.codepen.io/9394943/smiling-elves-christmas-clip-art-white-background.png', 'smiling-christmas-elves-clipart', 'https://assets.codepen.io/9394943/smiling-elves-christmas-clip-art-white-background.png', 'https://assets.codepen.io/9394943/smiling-elves-christmas-clip-art-white-background.png', true, CURRENT_TIMESTAMP, 'png', ARRAY['christmas']),
  ('Christmas Tree Cookie Clipart', 'christmas-tree-cookie-clipart', 'christmas-tree-cookie-clipart', 'christmas', 'https://assets.codepen.io/9394943/christmas-tree-cookie-wbg.png', 'christmas-tree-cookie-clipart', 'https://assets.codepen.io/9394943/christmas-tree-cookie-wbg.png', 'https://assets.codepen.io/9394943/christmas-tree-cookie-wbg.png', true, CURRENT_TIMESTAMP, 'png', ARRAY['christmas']),
  ('Santa Smile Icons Clipart', 'santa-smile-icons-clipart', 'santa-smile-icons-clipart', 'christmas', 'https://assets.codepen.io/9394943/santa-smiles-icons-white-bg.png', 'santa-smile-icons-clipart', 'https://assets.codepen.io/9394943/santa-smiles-icons-white-bg.png', 'https://assets.codepen.io/9394943/santa-smiles-icons-white-bg.png', true, CURRENT_TIMESTAMP, 'png', ARRAY['christmas']);

-- Halloween Images (6)
INSERT INTO images (title, slug, seo_slug, category, image_url, cloudinary_public_id, cloudinary_url, cloudinary_secure_url, published, published_at, file_format, tags)
VALUES 
  ('Witch Pencil Style Clipart', 'witch-pencil-style-clipart', 'witch-pencil-style-clipart', 'halloween', 'https://assets.codepen.io/9394943/witch-pencil-style-clip-art-white-bg.png', 'witch-pencil-style-clipart', 'https://assets.codepen.io/9394943/witch-pencil-style-clip-art-white-bg.png', 'https://assets.codepen.io/9394943/witch-pencil-style-clip-art-white-bg.png', true, CURRENT_TIMESTAMP, 'png', ARRAY['halloween']),
  ('Witch With Broomstick Halloween Clipart', 'witch-with-broomstick-halloween-clipart', 'witch-with-broomstick-halloween-clipart', 'halloween', 'https://assets.codepen.io/9394943/african-witch-with-broomstick-white-bg.png', 'witch-with-broomstick-halloween-clipart', 'https://assets.codepen.io/9394943/african-witch-with-broomstick-white-bg.png', 'https://assets.codepen.io/9394943/african-witch-with-broomstick-white-bg.png', true, CURRENT_TIMESTAMP, 'png', ARRAY['halloween']),
  ('Two Halloween Pumpkins Clipart', 'two-halloween-pumpkins-clipart', 'two-halloween-pumpkins-clipart', 'halloween', 'https://assets.codepen.io/9394943/two-halloween-clip-art-pumpkins-white-bg.png', 'two-halloween-pumpkins-clipart', 'https://assets.codepen.io/9394943/two-halloween-clip-art-pumpkins-white-bg.png', 'https://assets.codepen.io/9394943/two-halloween-clip-art-pumpkins-white-bg.png', true, CURRENT_TIMESTAMP, 'png', ARRAY['halloween']),
  ('Halloween Ghost Clipart', 'halloween-ghost-clipart', 'halloween-ghost-clipart', 'halloween', 'https://assets.codepen.io/9394943/halloween-clip-art-ghost-white-bg.png', 'halloween-ghost-clipart', 'https://assets.codepen.io/9394943/halloween-clip-art-ghost-white-bg.png', 'https://assets.codepen.io/9394943/halloween-clip-art-ghost-white-bg.png', true, CURRENT_TIMESTAMP, 'png', ARRAY['halloween']),
  ('Halloween Voodoo Dolls Clipart', 'halloween-voodoo-dolls-clipart', 'halloween-voodoo-dolls-clipart', 'halloween', 'https://assets.codepen.io/9394943/halloween-clipart-voodoo-dollas-white-bg.png', 'halloween-voodoo-dolls-clipart', 'https://assets.codepen.io/9394943/halloween-clipart-voodoo-dollas-white-bg.png', 'https://assets.codepen.io/9394943/halloween-clipart-voodoo-dollas-white-bg.png', true, CURRENT_TIMESTAMP, 'png', ARRAY['halloween']),
  ('Ghost And Pumpkin Halloween Clipart', 'ghost-and-pumpkin-halloween-clipart', 'ghost-and-pumpkin-halloween-clipart', 'halloween', 'https://assets.codepen.io/9394943/halloween-clipart-ghost-pumpkin-white-bg.png', 'ghost-and-pumpkin-halloween-clipart', 'https://assets.codepen.io/9394943/halloween-clipart-ghost-pumpkin-white-bg.png', 'https://assets.codepen.io/9394943/halloween-clipart-ghost-pumpkin-white-bg.png', true, CURRENT_TIMESTAMP, 'png', ARRAY['halloween']);

-- Flowers Images (6)
INSERT INTO images (title, slug, seo_slug, category, image_url, cloudinary_public_id, cloudinary_url, cloudinary_secure_url, published, published_at, file_format, tags)
VALUES 
  ('White Rose In Hair Flower Clipart', 'white-rose-in-hair-flower-clipart', 'white-rose-in-hair-flower-clipart', 'flowers', 'https://assets.codepen.io/9394943/white-rose-woman-hair-flower-clipart.png', 'white-rose-in-hair-flower-clipart', 'https://assets.codepen.io/9394943/white-rose-woman-hair-flower-clipart.png', 'https://assets.codepen.io/9394943/white-rose-woman-hair-flower-clipart.png', true, CURRENT_TIMESTAMP, 'png', ARRAY['flowers']),
  ('Colorful Roses Flower Clipart', 'colorful-roses-flower-clipart', 'colorful-roses-flower-clipart', 'flowers', 'https://assets.codepen.io/9394943/colorful-roses-flower-clipart.png', 'colorful-roses-flower-clipart', 'https://assets.codepen.io/9394943/colorful-roses-flower-clipart.png', 'https://assets.codepen.io/9394943/colorful-roses-flower-clipart.png', true, CURRENT_TIMESTAMP, 'png', ARRAY['flowers']),
  ('Girl Holding Flowers Clipart', 'girl-holding-flowers-clipart', 'girl-holding-flowers-clipart', 'flowers', 'https://assets.codepen.io/9394943/young-girl-holding-flowers-clipart-white-bg.png', 'girl-holding-flowers-clipart', 'https://assets.codepen.io/9394943/young-girl-holding-flowers-clipart-white-bg.png', 'https://assets.codepen.io/9394943/young-girl-holding-flowers-clipart-white-bg.png', true, CURRENT_TIMESTAMP, 'png', ARRAY['flowers']),
  ('Pink Rose Flower Clipart', 'pink-rose-flower-clipart', 'pink-rose-flower-clipart', 'flowers', 'https://assets.codepen.io/9394943/pink-rose-flower-clipart-white-bg.png', 'pink-rose-flower-clipart', 'https://assets.codepen.io/9394943/pink-rose-flower-clipart-white-bg.png', 'https://assets.codepen.io/9394943/pink-rose-flower-clipart-white-bg.png', true, CURRENT_TIMESTAMP, 'png', ARRAY['flowers']),
  ('Hawaiian Hibiscus Flower Clipart', 'hawaiian-hibiscus-flower-clipart', 'hawaiian-hibiscus-flower-clipart', 'flowers', 'https://assets.codepen.io/9394943/hawaiian-biscus-flower-clip-art.png', 'hawaiian-hibiscus-flower-clipart', 'https://assets.codepen.io/9394943/hawaiian-biscus-flower-clip-art.png', 'https://assets.codepen.io/9394943/hawaiian-biscus-flower-clip-art.png', true, CURRENT_TIMESTAMP, 'png', ARRAY['flowers']),
  ('Smiling Sunflower Emoji Clipart', 'smiling-sunflower-emoji-clipart', 'smiling-sunflower-emoji-clipart', 'flowers', 'https://assets.codepen.io/9394943/single-smiling-sunflower-emoji-flower-clipart.png', 'smiling-sunflower-emoji-clipart', 'https://assets.codepen.io/9394943/single-smiling-sunflower-emoji-flower-clipart.png', 'https://assets.codepen.io/9394943/single-smiling-sunflower-emoji-flower-clipart.png', true, CURRENT_TIMESTAMP, 'png', ARRAY['flowers']);

-- Cats Images (5)
INSERT INTO images (title, slug, seo_slug, category, image_url, cloudinary_public_id, cloudinary_url, cloudinary_secure_url, published, published_at, file_format, tags)
VALUES 
  ('Two Kittens Playing With Golf Balls Clipart', 'two-kittens-playing-with-golf-balls-clipart', 'two-kittens-playing-with-golf-balls-clipart', 'cats', 'https://assets.codepen.io/9394943/two-kittens-playing-with-golf-balls-in-paint-clip-art.png', 'two-kittens-playing-with-golf-balls-clipart', 'https://assets.codepen.io/9394943/two-kittens-playing-with-golf-balls-in-paint-clip-art.png', 'https://assets.codepen.io/9394943/two-kittens-playing-with-golf-balls-in-paint-clip-art.png', true, CURRENT_TIMESTAMP, 'png', ARRAY['cats']),
  ('Cute Kittens Holding Golf Clubs Clipart', 'cute-kittens-holding-golf-clubs-clipart', 'cute-kittens-holding-golf-clubs-clipart', 'cats', 'https://assets.codepen.io/9394943/cute-kittens-holding-golf-clubs-clip-art.png', 'cute-kittens-holding-golf-clubs-clipart', 'https://assets.codepen.io/9394943/cute-kittens-holding-golf-clubs-clip-art.png', 'https://assets.codepen.io/9394943/cute-kittens-holding-golf-clubs-clip-art.png', true, CURRENT_TIMESTAMP, 'png', ARRAY['cats']),
  ('Kitten Holding Dumbbell Clipart', 'kitten-holding-dumbbell-clipart', 'kitten-holding-dumbbell-clipart', 'cats', 'https://assets.codepen.io/9394943/kitten-holding-dumbbell-cat-clip-art.png', 'kitten-holding-dumbbell-clipart', 'https://assets.codepen.io/9394943/kitten-holding-dumbbell-cat-clip-art.png', 'https://assets.codepen.io/9394943/kitten-holding-dumbbell-cat-clip-art.png', true, CURRENT_TIMESTAMP, 'png', ARRAY['cats']),
  ('Cats In Fruit Basket Clipart', 'cats-in-fruit-basket-clipart', 'cats-in-fruit-basket-clipart', 'cats', 'https://assets.codepen.io/9394943/cats-laying-in-fruit-basket-clip-art.png', 'cats-in-fruit-basket-clipart', 'https://assets.codepen.io/9394943/cats-laying-in-fruit-basket-clip-art.png', 'https://assets.codepen.io/9394943/cats-laying-in-fruit-basket-clip-art.png', true, CURRENT_TIMESTAMP, 'png', ARRAY['cats']),
  ('Himalayan Kittens Playing Golf Clipart', 'himalayan-kittens-playing-golf-clipart', 'himalayan-kittens-playing-golf-clipart', 'cats', 'https://assets.codepen.io/9394943/cute-himalayan-kittens-playing-with-golf-balls-clip-art.png', 'himalayan-kittens-playing-golf-clipart', 'https://assets.codepen.io/9394943/cute-himalayan-kittens-playing-with-golf-balls-clip-art.png', 'https://assets.codepen.io/9394943/cute-himalayan-kittens-playing-with-golf-balls-clip-art.png', true, CURRENT_TIMESTAMP, 'png', ARRAY['cats']);

-- Verify the migration
SELECT category, COUNT(*) as image_count
FROM images
GROUP BY category
ORDER BY category;

